version: '3'
services:
  recommender:
    container_name: recommender-container
    build: .
    entrypoint: python s7rec/server.py
    ports:
      - '7777:7777'
    depends_on:
      - redis
  redis:
    image: redis
    container_name: redis-container
    ports:
      - "6379:6379"